version: "3"
services:
  testing-mongodb:
    image: mongo:latest
    container_name: testing-mongodb
    restart: always
    ports:
      - 27018:27017
    command: mongod --smallfiles --bind_ip_all
  prd-mongodb:
    image: mongo:latest
    container_name: prd-mongodb
    restart: always
    ports:
      - 27017:27017
    command: mongod --smallfiles --bind_ip_all --dbpath /data/db
  products-api:
    container_name: products-api
    build: ProductsApi
    depends_on:
      - testing-mongodb
      - prd-mongodb
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - ${WEB_API_PORT}:${WEB_API_PORT}
